name: Java CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Set up Android SDK Tools
        run: |
          echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH
      - name: Set up env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew dist
      - name: Upload built jar file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/advanced-dev-mode-{{ env.RELEASE_VERSION }}.jar
          tag: ${{ github.ref }}
